url: http://biljettapp.se
title: Biljettapp är till för dig som resenär
description: Håll järnkoll på din tågresa med en smart biljett i mobilen.
language: sv-se

author: Erik Eng
email: hej@biljettapp.se
github: biljettapp
twitter: biljettapp
facebook: biljettapp

analytics:
    profile: 36843230

permalink: /blogg/:title/

future: false
auto: true
server: true

sitemap:
    include: ["/index.html",
        "/integritetspolicy/index.html",
        "/passbook/index.html",
        "/api/index.html"]

exclude: ["README.md", "config.rb"]